# -*- coding: utf-8 -*-
"""OP

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11PoCLP4kmiseYQCOACLCfyw8wiGBpa0H

ONE PIECE EDA
1. Import Libraries
2. Load the Dataset
3. EDA
4. Visualization
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

data = pd.read_csv('/content/OnePieceArcs.csv')

data.head()

data.tail()

data.info()

max_chap = data[data['TotalEpisodes'] == data['TotalEpisodes'].max()] 
max_chap

data['Manga Percentage'] = data['Manga%'].apply(lambda x: float(x[:-1]))
data['Anime Percentage'] = data['Anime%'].apply(lambda x: float(x[:-1]))
data.drop(['Manga%', 'Anime%'], axis = 1, inplace = True)
data.head()

filler = data[data['Manga Percentage'] == 0]
filler

data.plot()
plt.rcParams['figure.figsize']=(15,8)

sns.barplot(x='Arc', y='TotalEpisodes', data=data)
plt.rcParams['figure.figsize']=(15,8)
plt.xticks(rotation=60)
plt.xlabel("Number of Episodes")
plt.ylabel("Arc Name")
plt.title("Arc vs Total Episode",fontsize=20)
plt.show()

sns.barplot(x='Arc', y='Start onEpisode', data=data)
plt.rcParams['figure.figsize']=(15,8)
plt.xticks(rotation=60)
plt.xlabel("Number of Episodes")
plt.ylabel("Arc Name")
plt.title("Arc vs Start onEpisode",fontsize=20)
plt.show()

sns.barplot(x='Arc', y='TotalPages', data=data)
plt.rcParams['figure.figsize']=(15,8)
plt.xticks(rotation=60)
plt.xlabel("Number of Episodes")
plt.ylabel("Arc Name")
plt.title("Arc vs TotalPages",fontsize=20)
plt.show()

corr = data.corr('kendall')
plt.figure(figsize=(20,10))
sns.heatmap(corr, vmin=1, vmax=1, linewidth= 0.5, annot=True)